name       : noctalia-qs
version    : 0.0.9
release    : 5
source     :
    - https://github.com/noctalia-dev/noctalia-qs/archive/refs/tags/v0.0.9.tar.gz : fccbf3d7b723df62610e6ba7fd1922701b52f7345f699b6a04c9c86b40e60f55
homepage   : https://github.com/noctalia-dev/noctalia-qs
license    : LGPL-3.0-only
component  : desktop.wayland
summary    : Flexible toolkit for making desktop shells with QtQuick (Noctalia fork)
description: |
    noctalia-qs is a custom fork of Quickshell, a flexible toolkit for making desktop
    shells with QtQuick, for Wayland and X11. It serves as the supported runtime
    for the Noctalia shell ecosystem, providing features and patches specific to
    Noctalia, such as ext-background-effect-v1 support.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(jemalloc)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcb)
    - pkgconfig(xkbcommon)
    - cli11
    - qt6-base-devel
    - qt6-base-private-devel
    - qt6-declarative-devel
    - qt6-shadertools-devel
    - qt6-wayland-devel
    - vulkan-headers
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release \
                 -DUSE_JEMALLOC=ON \
                 -DDISTRIBUTOR="DinimixisDEMZ" \
                 -DGIT_REVISION="v0.0.9" \
                 -DCRASH_REPORTER=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install