name: Update noctalia

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: "Put the package you want to build"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup Solbuild
      uses: GZGavinZhao/setup-solbuild@v1.1
      with:
        packager: "DinimixisDEMZ"
        
    - name: Set build environment
      shell: bash
      run: |
        echo "PACKAGE=${{ github.event.inputs.PACKAGE }}" >> $GITHUB_ENV

        chmod +x ./release.sh

    - name: Build package
      shell: bash
      run: |
        find . -name "*.eopkg" -type f -delete
        cd "$(pwd)/$PACKAGE"
        sudo solbuild build package.yml

    - name: Prepare release
      run: |
        bash ./release.sh

    - name: Uploading files to GitHub Release
      uses: softprops/action-gh-release@v2.6.1
      with:
        tag_name: "${{ github.event.inputs.PACKAGE }}-${{ github.run_id }}"
        name: "${{ github.event.inputs.PACKAGE }} Build: ${{ github.run_id }}"
        body: |
            ***Build Information***
            - ➡️ Package: ${{ github.event.inputs.PACKAGE }}
            - Size: ${{ env.SIZE }}
            - MD5: ${{ env.MD5 }}
        files: |
          Releases/*

    - name: Cleanup
      run: |
        sudo rm -rf *
