name: Update noctalia

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: "Put the package you want to build"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: setup-solbuild
      uses: GZGavinZhao/setup-solbuild@v1.1
      with:
        packager: "DinimixisDEMZ"
        
    - name: Set build environment
      shell: bash
      run: |
        echo "PACKAGE=${{ github.event.inputs.PACKAGE }}" >> $GITHUB_ENV

    - name: Install required packages
      run: |
        sudo apt install -y \
          python3 python3-pip git golang bzr

        chmod +x ./release.sh

    - name: Build package
      shell: bash
      run: |
        find . -name "*.eopkg" -type f -delete
        cd "$(pwd)/$PACKAGE"
        sudo solbuild build package.yml

    - name: Create release
      env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        cd
        sudo bash ./release.sh

    - name: Cleanup
      run: |
        sudo rm -rf *
