name: Update noctalia

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: setup-solbuild
      uses: GZGavinZhao/setup-solbuild@v1.1
